[profile.default]
src = 'contracts'
out = 'forge-artifacts'
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@eth-optimism/contracts-bedrock/=node_modules/@eth-optimism/contracts-bedrock',
  '@eth-optimism/contracts/=node_modules/@eth-optimism/contracts',
  '@thirdweb-dev/contracts/=node_modules/@thirdweb-dev/contracts',
  '@connext/interfaces=node_modules/@connext/interfaces/',
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/'
]

gas_price=1
