[profile.default]
src = 'contracts'
fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 2
ffi = true
solc = '0.8.4'
optimizer = false
test = 'test'
script = 'scripts'
extra_output=['storageLayout']
remappings = [
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  'ds-test/=node_modules/ds-test/src/',
  '@gnosis.pm/safe-contracts-1.3.0/=node_modules/@gnosis.pm/safe-contracts/contracts/',
  '@gnosis.pm/safe-contracts-1.4.1/=node_modules/@gnosis.pm/safe-contracts-1.4.1/contracts/'
]
always_use_create_2_factory = true
libs = []

[profile.core]
src = 'contracts/core'

[profile.lite]
optimizer = false

[rpc_endpoints]
ethereum = 'http://127.0.0.1:42001'
optimism = 'http://127.0.0.1:42010'

[fmt]
line_length=100
multiline_func_header="all"
bracket_spacing=true
wrap_comments=true
